/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ahmet
 */
import java.sql.Connection;// bağlantı için
import java.sql.PreparedStatement; // sql sorgularını veritabanına taşımak için
import java.sql.ResultSet; // select sorgusu sonuçlarını almak için
import java.sql.Timestamp;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.Date;

public class RYS extends javax.swing.JFrame {

    Connection conn;
    PreparedStatement pst;
    ResultSet rs;
    double[] fiyatlar = {0, 0, 0, 0, 0, 0};
    double firstnum, secondnum, result;
    String operator;

    /* fiyatlar[0]:içecek; fiyatlar[1]:yiyececek;fiyatlar[2]:bahsis
       fiyatlar[3]:KDV;    fiyatlar[4]:aratoplam;fiyatlar[5]:geneltoplam */
    /**
     *
     *
     * fiyatlar[0]=0 Creates new form RYS
     */
    public RYS() {
        initComponents();
        jTabbedPane1.setSelectedIndex(1); // Faturayı tabbedPane de ikinci kısma eklemişim ama default olarak fatura kısmının açılmasını istiyorum
        cb_doldur("SELECT * FROM Doviz", cb_kur);

    }

    void cb_doldur(String sql, javax.swing.JComboBox<String> cb) {
        conn = db.java_db(); // 1. veritabanına bağlanır
        try {
            //String sql = "SELECT * FROM Doviz"; // 2. sql sorgusy oluşturulur
            pst = conn.prepareStatement(sql);// 3. sql sorgusu preparedstatement objesine aktarılır
            rs = pst.executeQuery(); // 4. sorgu çalıştırılır ve resultset rs'ye aktarılır
            while (rs.next()) // sonuçları tek tek oku
            {
                cb.addItem(rs.getString(2));
            }
        } catch (Exception ex) {
            //
        } finally {
            try {
                conn.close(); // 5.bağlantı kapatılır
            } catch (Exception ex) {
                //
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_hesapla = new javax.swing.JButton();
        cb_kur = new javax.swing.JComboBox<>();
        lbl_dekran = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_icecek = new javax.swing.JLabel();
        lbl_yemek = new javax.swing.JLabel();
        lbl_bahsis = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        ck_iskender = new javax.swing.JCheckBox();
        txt_iskender = new javax.swing.JTextField();
        ck_tavuk = new javax.swing.JCheckBox();
        txt_tavuk = new javax.swing.JTextField();
        ck_et = new javax.swing.JCheckBox();
        txt_et = new javax.swing.JTextField();
        ck_bahsis = new javax.swing.JCheckBox();
        txt_bahsis = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        ck_kola = new javax.swing.JCheckBox();
        txt_kola = new javax.swing.JTextField();
        ck_ayran = new javax.swing.JCheckBox();
        txt_ayran = new javax.swing.JTextField();
        ck_soda = new javax.swing.JCheckBox();
        txt_soda = new javax.swing.JTextField();
        txt_su = new javax.swing.JTextField();
        ck_su = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        lbl_aratoplam = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbl_kdv = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbl_geneltoplam = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btn_toplamhesap = new javax.swing.JButton();
        btn_fatura = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        btn_kapat = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        txt_ekran = new javax.swing.JTextField();
        b_del = new javax.swing.JButton();
        b_c = new javax.swing.JButton();
        b_tersal = new javax.swing.JButton();
        b_topla = new javax.swing.JButton();
        b_7 = new javax.swing.JButton();
        b_8 = new javax.swing.JButton();
        b_9 = new javax.swing.JButton();
        b_cikar = new javax.swing.JButton();
        b_4 = new javax.swing.JButton();
        b_5 = new javax.swing.JButton();
        b_6 = new javax.swing.JButton();
        b_carp = new javax.swing.JButton();
        b_1 = new javax.swing.JButton();
        b_2 = new javax.swing.JButton();
        b_3 = new javax.swing.JButton();
        b_bol = new javax.swing.JButton();
        b_0 = new javax.swing.JButton();
        b_dot = new javax.swing.JButton();
        b_esittir = new javax.swing.JButton();
        b_mod = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtarea_fatura = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("RESTAURANT YÖNETİM SİSTEMİ");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        btn_hesapla.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_hesapla.setText("Hesapla");
        btn_hesapla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_hesapla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hesaplaActionPerformed(evt);
            }
        });

        cb_kur.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cb_kur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seçiniz" }));
        cb_kur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_kurActionPerformed(evt);
            }
        });

        lbl_dekran.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_dekran.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_dekran.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Döviz Ödemesi İçin Hesaplama");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(lbl_dekran, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cb_kur, 0, 127, Short.MAX_VALUE)
                    .addComponent(btn_hesapla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(cb_kur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(btn_hesapla, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(lbl_dekran, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("İçecek");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Yemek");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Bahşiş");

        lbl_icecek.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_icecek.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lbl_yemek.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_yemek.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lbl_bahsis.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_bahsis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_icecek, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(lbl_yemek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_bahsis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_icecek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_yemek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_bahsis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        ck_iskender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ck_iskender.setText("İskender");
        ck_iskender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ck_iskenderActionPerformed(evt);
            }
        });

        txt_iskender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_iskender.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ck_tavuk.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ck_tavuk.setText("Tavuk Döner");
        ck_tavuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ck_tavukActionPerformed(evt);
            }
        });

        txt_tavuk.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_tavuk.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ck_et.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ck_et.setText("Et Döner");
        ck_et.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ck_etActionPerformed(evt);
            }
        });

        txt_et.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_et.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ck_bahsis.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ck_bahsis.setText("Bahşiş");
        ck_bahsis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ck_bahsisActionPerformed(evt);
            }
        });

        txt_bahsis.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_bahsis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_bahsis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bahsisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ck_iskender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ck_tavuk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_tavuk, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(txt_iskender, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ck_et, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ck_bahsis, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_et, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_bahsis))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ck_iskender, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_iskender, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ck_tavuk, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tavuk, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_et, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ck_et, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ck_bahsis)
                    .addComponent(txt_bahsis, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        jTabbedPane3.addTab("Yiyecekler", jPanel5);

        ck_kola.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ck_kola.setText("Kola");
        ck_kola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ck_kolaActionPerformed(evt);
            }
        });

        txt_kola.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_kola.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_kola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kolaActionPerformed(evt);
            }
        });

        ck_ayran.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ck_ayran.setText("Ayran");
        ck_ayran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ck_ayranActionPerformed(evt);
            }
        });

        txt_ayran.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_ayran.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ck_soda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ck_soda.setText("Soda");
        ck_soda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ck_sodaActionPerformed(evt);
            }
        });

        txt_soda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_soda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txt_su.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_su.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ck_su.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ck_su.setText("Su");
        ck_su.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ck_suActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ck_su, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ck_soda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ck_ayran, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(ck_kola, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt_soda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(txt_ayran, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_su)
                    .addComponent(txt_kola, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ck_kola, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_kola, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ck_ayran, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ayran, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ck_soda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_soda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ck_su, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_su, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("İçecekler", jPanel10);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Ara Toplam");

        lbl_aratoplam.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_aratoplam.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("KDV");

        lbl_kdv.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_kdv.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Toplam");

        lbl_geneltoplam.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_geneltoplam.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_aratoplam, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(lbl_kdv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_geneltoplam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_aratoplam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_kdv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_geneltoplam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        btn_toplamhesap.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_toplamhesap.setText("TOPLAM");
        btn_toplamhesap.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_toplamhesap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_toplamhesapActionPerformed(evt);
            }
        });

        btn_fatura.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_fatura.setText("FATURA");
        btn_fatura.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_fatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_faturaActionPerformed(evt);
            }
        });

        btn_reset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_reset.setText("RESET");
        btn_reset.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        btn_kapat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_kapat.setText("KAPAT");
        btn_kapat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_kapat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kapatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(btn_toplamhesap, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(btn_fatura, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(btn_kapat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_toplamhesap, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_fatura, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_kapat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        txt_ekran.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_ekran.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_ekran.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txt_ekran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ekranActionPerformed(evt);
            }
        });

        b_del.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b_del.setText("Del");
        b_del.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_delActionPerformed(evt);
            }
        });

        b_c.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b_c.setText("C");
        b_c.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cActionPerformed(evt);
            }
        });

        b_tersal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b_tersal.setText("+/-");
        b_tersal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_tersal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_tersalActionPerformed(evt);
            }
        });

        b_topla.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b_topla.setText("+");
        b_topla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_topla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_toplaActionPerformed(evt);
            }
        });

        b_7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b_7.setText("7");
        b_7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_7ActionPerformed(evt);
            }
        });

        b_8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b_8.setText("8");
        b_8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_8ActionPerformed(evt);
            }
        });

        b_9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b_9.setText("9");
        b_9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_9ActionPerformed(evt);
            }
        });

        b_cikar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b_cikar.setText("-");
        b_cikar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_cikar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cikarActionPerformed(evt);
            }
        });

        b_4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b_4.setText("4");
        b_4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_4ActionPerformed(evt);
            }
        });

        b_5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b_5.setText("5");
        b_5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_5ActionPerformed(evt);
            }
        });

        b_6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b_6.setText("6");
        b_6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_6ActionPerformed(evt);
            }
        });

        b_carp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b_carp.setText("*");
        b_carp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_carp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_carpActionPerformed(evt);
            }
        });

        b_1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b_1.setText("1");
        b_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_1ActionPerformed(evt);
            }
        });

        b_2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b_2.setText("2");
        b_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_2ActionPerformed(evt);
            }
        });

        b_3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b_3.setText("3");
        b_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_3ActionPerformed(evt);
            }
        });

        b_bol.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b_bol.setText("/");
        b_bol.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_bol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_bolActionPerformed(evt);
            }
        });

        b_0.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b_0.setText("0");
        b_0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_0ActionPerformed(evt);
            }
        });

        b_dot.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b_dot.setText(".");
        b_dot.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_dotActionPerformed(evt);
            }
        });

        b_esittir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b_esittir.setText("=");
        b_esittir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_esittir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_esittirActionPerformed(evt);
            }
        });

        b_mod.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b_mod.setText("%");
        b_mod.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_modActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txt_ekran)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addComponent(b_del, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(b_c, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(b_tersal, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(b_topla, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(b_7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_cikar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(b_4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_carp, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(b_1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_bol, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(b_0, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_dot, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_esittir, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(txt_ekran, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_del, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_c, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_tersal, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_topla, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_cikar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_carp, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_bol, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_0, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_dot, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_esittir, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Hesap Makinesi", jPanel8);

        txtarea_fatura.setColumns(20);
        txtarea_fatura.setRows(5);
        jScrollPane1.setViewportView(txtarea_fatura);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Fatura", jPanel9);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(87, 87, 87))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(15, 15, 15)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_4ActionPerformed
        degerekle(b_4);
    }//GEN-LAST:event_b_4ActionPerformed

    private void btn_hesaplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hesaplaActionPerformed
        try {
            String ttutar = lbl_geneltoplam.getText();
            String ttutar2 = ttutar.replace(" TL", "");
            double toplam_tutar = Double.parseDouble(ttutar2);
            int kur_secenek = cb_kur.getSelectedIndex();
            conn = db.java_db();
            String sql = "SELECT * FROM Doviz WHERE id='" + kur_secenek + "'";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            double kurfiyat = Double.parseDouble(rs.getString("kur_fiyat"));
            String kurad = rs.getString("kur_ad");
            double sonuc = (toplam_tutar / kurfiyat);
            lbl_dekran.setText(String.format("%.2f %s", sonuc, kurad));
        } catch (Exception ex) {

        } finally {
            try {
                conn.close(); // 5.bağlantı kapatılır
            } catch (Exception ex) {
                //
            }
        }
    }//GEN-LAST:event_btn_hesaplaActionPerformed

    ResultSet rsdondur(String sql) {
        try {
            conn = db.java_db();
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            return rs;
        } catch (Exception ex) {
            return null;
        }
    }

    void yiyecekhesapla(javax.swing.JTextField txt, javax.swing.JCheckBox ck) {
        try {
            int adet = Integer.parseInt(txt.getText());
            conn = db.java_db();
            String sql = "SELECT * FROM Yemekler WHERE yemekad='" + ck.getText() + "'";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            double fiyat = Double.parseDouble(rs.getString("yemekfiyat"));
            if (ck.isSelected()) {
                fiyatlar[1] = fiyatlar[1] + fiyat * adet;
                lbl_yemek.setText(String.format("%.2f TL", fiyatlar[1]));
                txt.setEnabled(false);
            } else {
                fiyatlar[1] = fiyatlar[1] - fiyat * adet;
                lbl_yemek.setText(String.format("%.2f TL", fiyatlar[1]));
                txt.setEnabled(true);
            }
        } catch (Exception ex) {

        } finally {
            try {
                conn.close();
            } catch (Exception ex) {

            }
        }
    }

    void icecekhesapla(javax.swing.JTextField txt, javax.swing.JCheckBox ck) {
        try {
            int adet = Integer.parseInt(txt.getText());
            conn = db.java_db();
            String sql = "SELECT * FROM Icecekler WHERE icecekad='" + ck.getText() + "'";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            double fiyat = Double.parseDouble(rs.getString("icecekfiyat"));
            if (ck.isSelected()) {
                fiyatlar[0] = fiyatlar[0] + fiyat * adet;
                lbl_icecek.setText(String.format("%.2f TL", fiyatlar[0]));
                txt.setEnabled(false);
            } else {
                fiyatlar[0] = fiyatlar[0] - fiyat * adet;
                lbl_icecek.setText(String.format("%.2f TL", fiyatlar[0]));
                txt.setEnabled(true);
            }
        } catch (Exception ex) {

        } finally {
            try {
                conn.close();
            } catch (Exception ex) {

            }
        }
    }

    /* fiyatlar[0]:içecek; fiyatlar[1]:yiyececek;fiyatlar[2]:bahsis
       fiyatlar[3]:KDV;    fiyatlar[4]:aratoplam;fiyatlar[5]:geneltoplam */

    private void btn_toplamhesapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_toplamhesapActionPerformed
        fiyatlar[3] = (fiyatlar[0] + fiyatlar[1] + fiyatlar[2]) * 0.18;
        fiyatlar[4] = fiyatlar[0] + fiyatlar[1] + fiyatlar[2]; //aratoplam
        fiyatlar[5] = fiyatlar[4] + fiyatlar[3];
        lbl_kdv.setText(String.format("%.2f TL", fiyatlar[3]));
        lbl_aratoplam.setText(String.format("%.2f TL", fiyatlar[4]));
        lbl_geneltoplam.setText((fiyatlar[5]) + " TL");/* Burada tl'yi %.2f ile yazırmadım çünkü döviz hesaplarken
            String ifadeyi atamadım
         */



    }//GEN-LAST:event_btn_toplamhesapActionPerformed

    private void btn_faturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_faturaActionPerformed
        if (lbl_geneltoplam.getText().length() > 0) {
            txtarea_fatura.setText("");
            DateFormat sdf = new SimpleDateFormat("dd/MM/YYYY HH:mm:ss");
            Date tarih = new Date();
            txtarea_fatura.append("Restaurant Yönetim Sistemi: \n\n"
                    + sdf.format(tarih)
                    + "\n\nİçecek Fiyatı: \t" + lbl_icecek.getText()
                    + "\nYemek Fiyat: \t" + lbl_yemek.getText()
                    + "\nAra Toplam: \t" + lbl_aratoplam.getText()
                    + "\nGenel Toplam: \t" + lbl_geneltoplam.getText()
            );

            try {
                conn = db.java_db();
                String sql = "INSERT INTO Islemler (icecekfiyat,yemekfiyat,bahsis,kdv,aratoplam,toplam,tarih) "
                        + "VALUES(?,?,?,?,?,?,?)";
                pst = conn.prepareStatement(sql);
                pst.setString(1, String.valueOf(fiyatlar[0]));
                pst.setString(2, String.valueOf(fiyatlar[1]));
                pst.setString(3, String.valueOf(fiyatlar[2]));
                pst.setString(4, String.valueOf(fiyatlar[3]));
                pst.setString(5, String.valueOf(fiyatlar[4]));
                pst.setString(6, String.valueOf(fiyatlar[5]));
                pst.setString(7, sdf.format(tarih));

                pst.execute(); // INSERT, UPDATE ve DELETE sorguları için
                // rs=pst.executequery(); SELECT sorgusunda kullanılır
                JOptionPane.showMessageDialog(null, "Kayıt başarıyla eklenmiştir.");
            } catch (Exception ex) {

            } finally {
                try {
                    conn.close();
                } catch (Exception ex) {

                }
            }

        } else {
            JOptionPane.showMessageDialog(null, "Lütfen genel toplam hesabını yapınız'");
        }
    }//GEN-LAST:event_btn_faturaActionPerformed

    private void btn_kapatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kapatActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_kapatActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        txt_tavuk.setText("");
        txt_et.setText("");
        txt_iskender.setText("");
        txt_tavuk.setEnabled(true);
        txt_et.setEnabled(true);
        txt_iskender.setEnabled(true);
        lbl_icecek.setText("");
        lbl_yemek.setText("");
        lbl_bahsis.setText("");
        lbl_kdv.setText(null);
        lbl_aratoplam.setText("");
        lbl_geneltoplam.setText("");
        ck_tavuk.setSelected(false);
        ck_et.setSelected(false);
        ck_iskender.setSelected(false);
        txt_kola.setText("");
        txt_ayran.setText("");
        txt_soda.setText("");
        txt_su.setText("");
        txt_kola.setEnabled(true);
        txt_ayran.setEnabled(true);
        txt_soda.setEnabled(true);
        txt_su.setEnabled(true);
        ck_kola.setSelected(false);
        ck_ayran.setSelected(false);
        ck_soda.setSelected(false);
        ck_su.setSelected(false);
        txt_bahsis.setText("");
        txt_bahsis.setEnabled(true);
        ck_bahsis.setSelected(false);
        lbl_dekran.setText("");

        txtarea_fatura.setText("");

        for (int i = 0; i < fiyatlar.length; i++) {
            fiyatlar[i] = 0;
        }
    }//GEN-LAST:event_btn_resetActionPerformed
    void degerekle(javax.swing.JButton btn) {
        String deger = txt_ekran.getText() + btn.getText();
        txt_ekran.setText(deger);
    }
    private void b_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_7ActionPerformed
        degerekle(b_7);
    }//GEN-LAST:event_b_7ActionPerformed

    private void b_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_8ActionPerformed
        degerekle(b_8);
    }//GEN-LAST:event_b_8ActionPerformed

    private void b_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_9ActionPerformed
        degerekle(b_9);
    }//GEN-LAST:event_b_9ActionPerformed

    private void b_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_5ActionPerformed
        degerekle(b_5);
    }//GEN-LAST:event_b_5ActionPerformed

    private void b_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_6ActionPerformed
        degerekle(b_6);
    }//GEN-LAST:event_b_6ActionPerformed

    private void b_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_1ActionPerformed
        degerekle(b_1);
    }//GEN-LAST:event_b_1ActionPerformed

    private void b_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_2ActionPerformed
        degerekle(b_2);
    }//GEN-LAST:event_b_2ActionPerformed

    private void b_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_3ActionPerformed
        degerekle(b_3);
    }//GEN-LAST:event_b_3ActionPerformed

    private void b_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_0ActionPerformed
        degerekle(b_0);
    }//GEN-LAST:event_b_0ActionPerformed

    private void b_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_delActionPerformed
        if (txt_ekran.getText().length() > 0) {
            StringBuffer stb = new StringBuffer(txt_ekran.getText());
            stb.deleteCharAt(stb.length() - 1);
            txt_ekran.setText(stb.toString());
        }
    }//GEN-LAST:event_b_delActionPerformed

    private void b_toplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_toplaActionPerformed
        firstnum = Double.parseDouble(txt_ekran.getText());
        operator = "Toplama";
        txt_ekran.setText(null);
    }//GEN-LAST:event_b_toplaActionPerformed

    private void ck_iskenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ck_iskenderActionPerformed
        yiyecekhesapla(txt_iskender, ck_iskender);
    }//GEN-LAST:event_ck_iskenderActionPerformed

    private void ck_tavukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ck_tavukActionPerformed
        yiyecekhesapla(txt_tavuk, ck_tavuk);
    }//GEN-LAST:event_ck_tavukActionPerformed

    private void ck_etActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ck_etActionPerformed
        yiyecekhesapla(txt_et, ck_et);
    }//GEN-LAST:event_ck_etActionPerformed

    private void ck_kolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ck_kolaActionPerformed
        icecekhesapla(txt_kola, ck_kola);
    }//GEN-LAST:event_ck_kolaActionPerformed

    private void ck_ayranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ck_ayranActionPerformed
        icecekhesapla(txt_ayran, ck_ayran);
    }//GEN-LAST:event_ck_ayranActionPerformed

    private void ck_sodaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ck_sodaActionPerformed
        icecekhesapla(txt_soda, ck_soda);
    }//GEN-LAST:event_ck_sodaActionPerformed

    private void ck_suActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ck_suActionPerformed
        icecekhesapla(txt_su, ck_su);
    }//GEN-LAST:event_ck_suActionPerformed

    private void txt_kolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kolaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kolaActionPerformed

    private void ck_bahsisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ck_bahsisActionPerformed
        if (ck_bahsis.isSelected()) {
            int bahsis_miktari = Integer.parseInt(txt_bahsis.getText());
            fiyatlar[2] = bahsis_miktari;
            lbl_bahsis.setText(String.format("%.2f TL", fiyatlar[2]));
        } else {
            fiyatlar[2] = 0;
            lbl_bahsis.setText(String.format("%.2f TL", fiyatlar[2]));
        }
    }//GEN-LAST:event_ck_bahsisActionPerformed

    private void txt_bahsisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bahsisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bahsisActionPerformed

    private void cb_kurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_kurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_kurActionPerformed

    private void b_esittirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_esittirActionPerformed
      try { 
       secondnum = Double.parseDouble(txt_ekran.getText());
   }
   catch(Exception ex){
       JOptionPane.showMessageDialog(null,"Lütfen 2. sayıyı giriniz");
           return; 
}
            
          switch (operator) {
              case "Toplama":
                  result = firstnum + secondnum;
                  break;
              case "Cikarma":
                  result = firstnum - secondnum;
                  break;
              case "Carpma":
                  result = firstnum * secondnum;
                  break;
              case "Bolme":
                  result = firstnum / secondnum;
                  break;
              case "Mod":
                  result = firstnum % secondnum;
                  break;
              default:
                  break;
          }
        txt_ekran.setText(String.valueOf(result)); 
   // TODO add your handling code here:
    }//GEN-LAST:event_b_esittirActionPerformed

    private void b_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cActionPerformed
        txt_ekran.setText(null);
        operator = null;
        firstnum = 0;
        secondnum = 0;
        result = 0;
    }//GEN-LAST:event_b_cActionPerformed

    private void b_tersalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_tersalActionPerformed
        Double num = Double.parseDouble(txt_ekran.getText());
        if (num != 0) {
            num = num * (-1);
            txt_ekran.setText(String.valueOf(num));
        }
    }//GEN-LAST:event_b_tersalActionPerformed

    private void b_cikarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cikarActionPerformed
        firstnum = Double.parseDouble(txt_ekran.getText());
        operator = "Cikarma";
        txt_ekran.setText(null);
    }//GEN-LAST:event_b_cikarActionPerformed

    private void b_carpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_carpActionPerformed
        firstnum = Double.parseDouble(txt_ekran.getText());
        operator = "Carpma";
        txt_ekran.setText(null);
    }//GEN-LAST:event_b_carpActionPerformed

    private void b_bolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_bolActionPerformed
        firstnum = Double.parseDouble(txt_ekran.getText());
        operator = "Bolme";
        txt_ekran.setText(null);
    }//GEN-LAST:event_b_bolActionPerformed

    private void b_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_modActionPerformed
        firstnum = Double.parseDouble(txt_ekran.getText());
        operator = "Mod";
        txt_ekran.setText(null);
    }//GEN-LAST:event_b_modActionPerformed

    private void b_dotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_dotActionPerformed
    StringBuffer stb= new StringBuffer(txt_ekran.getText());
        if (stb.indexOf(".")<0) {//nokta yoksa
            degerekle(b_dot);
            }          // TODO add your handling code here:
    }//GEN-LAST:event_b_dotActionPerformed

    private void txt_ekranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ekranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ekranActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RYS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RYS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RYS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RYS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RYS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_0;
    private javax.swing.JButton b_1;
    private javax.swing.JButton b_2;
    private javax.swing.JButton b_3;
    private javax.swing.JButton b_4;
    private javax.swing.JButton b_5;
    private javax.swing.JButton b_6;
    private javax.swing.JButton b_7;
    private javax.swing.JButton b_8;
    private javax.swing.JButton b_9;
    private javax.swing.JButton b_bol;
    private javax.swing.JButton b_c;
    private javax.swing.JButton b_carp;
    private javax.swing.JButton b_cikar;
    private javax.swing.JButton b_del;
    private javax.swing.JButton b_dot;
    private javax.swing.JButton b_esittir;
    private javax.swing.JButton b_mod;
    private javax.swing.JButton b_tersal;
    private javax.swing.JButton b_topla;
    private javax.swing.JButton btn_fatura;
    private javax.swing.JButton btn_hesapla;
    private javax.swing.JButton btn_kapat;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_toplamhesap;
    private javax.swing.JComboBox<String> cb_kur;
    private javax.swing.JCheckBox ck_ayran;
    private javax.swing.JCheckBox ck_bahsis;
    private javax.swing.JCheckBox ck_et;
    private javax.swing.JCheckBox ck_iskender;
    private javax.swing.JCheckBox ck_kola;
    private javax.swing.JCheckBox ck_soda;
    private javax.swing.JCheckBox ck_su;
    private javax.swing.JCheckBox ck_tavuk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JLabel lbl_aratoplam;
    private javax.swing.JLabel lbl_bahsis;
    private javax.swing.JLabel lbl_dekran;
    private javax.swing.JLabel lbl_geneltoplam;
    private javax.swing.JLabel lbl_icecek;
    private javax.swing.JLabel lbl_kdv;
    private javax.swing.JLabel lbl_yemek;
    private javax.swing.JTextField txt_ayran;
    private javax.swing.JTextField txt_bahsis;
    private javax.swing.JTextField txt_ekran;
    private javax.swing.JTextField txt_et;
    private javax.swing.JTextField txt_iskender;
    private javax.swing.JTextField txt_kola;
    private javax.swing.JTextField txt_soda;
    private javax.swing.JTextField txt_su;
    private javax.swing.JTextField txt_tavuk;
    private javax.swing.JTextArea txtarea_fatura;
    // End of variables declaration//GEN-END:variables
}
